spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.99.43.121:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
logging:
  level:
    root: info
    com.star: debug
  file:
    name: log/blog-dev.log


mybatis:
  type-aliases-package: com.lys.lys_blog.pojo
  mapper-locations: classpath:com.lys.lys_blog.ampper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#配置端口
server:
  port: 8080