spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
comment.avatar: ../images/avatar.png
message.avatar: ../images/avatar.png
server:
  port: 8080
  datasource:
    data: classpath:myblog.sql
